version: '3.9'
services:
  gogs:
    image: gogs/gogs:0.13.0@sha256:730c521a280c0c6acd18f7b4335acc1a6ffc5ad31f872d5a193317b47a62eb90
    hostname: gogs
    container_name: gogs__gogs
    restart: unless-stopped

    environment:
      TZ: JST

    volumes:
      - type: volume
        source: gogs_data
        target: /data

    expose:
      - 3000

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 512m

  mariadb:
    image: mariadb:11.1.2@sha256:5d851e999b84625ef9810589e832686cae58453452698ee69e2980041e626eb2

    hostname: mariadb
    container_name: gogs__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
      MYSQL_DATABASE: gogs

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 512m

  cloudflared:
    image: cloudflare/cloudflared:2023.8.2@sha256:93561dfa0032006354be56476f09e3d8743d53d202368672c2847c1631f7be50
    hostname: cloudflared
    container_name: gogs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - gogs__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  gogs_data:
    name: gogs__gogs_data
  mariadb_data:
    name: gogs__mariadb_data

networks:
  default:
    name: gogs__default
    internal: true

  outband:
    name: gogs__outband

  prometheus__cloudflared:
    name: prometheus__cloudflared 
    external: true
