version: '3.9'
services:
  gogs:
    image: gogs/gogs:0.12.10@sha256:a791aed48a964db11f78095d154e74aaaa14e1a40de16900bfd1383ca071bdac
    hostname: gogs
    container_name: gogs__gogs
    restart: unless-stopped

    environment:
      TZ: JST

    volumes:
      - type: volume
        source: gogs_data
        target: /data

    expose:
      - 3000

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 512m

  mariadb:
    image: mariadb:10.10.3@sha256:0d81a2fd3df954f1f29016a841b0d4cb5bdbc7eb7c640156d3dddd48c6ace35b

    hostname: mariadb
    container_name: gogs__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
      MYSQL_DATABASE: gogs

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 512m

  cloudflared:
    image: cloudflare/cloudflared:2023.2.1@sha256:5235e62dc2f4afe707355a3ab30babe0f15523bba12bce496e7259ad4eb580d1
    hostname: cloudflared
    container_name: gogs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - gogs__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  gogs_data:
    name: gogs__gogs_data
  mariadb_data:
    name: gogs__mariadb_data

networks:
  default:
    name: gogs__default
    internal: true

  outband:
    name: gogs__outband

  prometheus__cloudflared:
    name: prometheus__cloudflared 
    external: true
