version: '3.9'
services:
  gogs:
    image: gogs/gogs:0.13.0@sha256:730c521a280c0c6acd18f7b4335acc1a6ffc5ad31f872d5a193317b47a62eb90
    hostname: gogs
    container_name: gogs__gogs
    restart: unless-stopped

    environment:
      TZ: JST

    volumes:
      - type: volume
        source: gogs_data
        target: /data

    expose:
      - 3000

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 512m

  mariadb:
    image: mariadb:11.2.2@sha256:4d5a0e687d469b1a1e08ea8829f46ef1d966d9e0a3a8f3613fcf61e933161c27

    hostname: mariadb
    container_name: gogs__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
      MYSQL_DATABASE: gogs

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 512m

  cloudflared:
    image: cloudflare/cloudflared:2023.10.0@sha256:c18744ae1767c17c5562cc731c24e64a5a2f93f35c3dd6629b90dedaff6dff8f
    hostname: cloudflared
    container_name: gogs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - gogs__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  gogs_data:
    name: gogs__gogs_data
  mariadb_data:
    name: gogs__mariadb_data

networks:
  default:
    name: gogs__default
    internal: true

  outband:
    name: gogs__outband

  prometheus__cloudflared:
    name: prometheus__cloudflared 
    external: true
