version: '3.9'
services:
  gogs:
    image: gogs/gogs:0.12.10@sha256:a791aed48a964db11f78095d154e74aaaa14e1a40de16900bfd1383ca071bdac
    hostname: gogs
    container_name: gogs__gogs
    restart: unless-stopped

    environment:
      TZ: JST

    volumes:
      - type: volume
        source: gogs_data
        target: /data

    expose:
      - 3000

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 512m

  mariadb:
    image: mariadb:10.10.2@sha256:569cda3a16fbd0235d20a0f895c9a906e022a75eeeb836da6c29f9a542cccf75

    hostname: mariadb
    container_name: gogs__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
      MYSQL_DATABASE: gogs

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 512m

  cloudflared:
    image: cloudflare/cloudflared:2023.1.0@sha256:11101e453ddcd33b7c2175de701c3d29c11b401fe14b74e6c8f371d65fe7558a
    hostname: cloudflared
    container_name: gogs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - gogs__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  gogs_data:
    name: gogs__gogs_data
  mariadb_data:
    name: gogs__mariadb_data

networks:
  default:
    name: gogs__default
    internal: true

  outband:
    name: gogs__outband

  prometheus__cloudflared:
    name: prometheus__cloudflared 
    external: true
